INSERT INTO BookReviews (BookID, Rating, MemberID, Comment)
VALUES 
(1, 5, 1, 'The symbolism in this book is mesmerizing!'),
(1, 3, 2, 'This book ignited my imagination!'),
(1, 5, 7, 'Santiago''s journey inspired me to chase my dreams.'),
(1, 5, 5, 'Harper Lee''s writing is timeless'),
(2, 3, 2, 'Hogwarts feels like home.'),
(2, 3, 4, 'Atticus Finch is the epitome of integrity.'),
(2, 4, 9, 'Fitzgerald''s writing style is captivating'),
(2, 5, 10, 'Coelho''s storytelling is profound.'),
(3, 3, 3, 'Rowling''s world-building is unparalleled.'),
(3, 3, 2, 'I enjoyed unraveling the characters'' secrets'),
(3, 4, 1, 'The lessons about following one''s heart resonated deeply.'),
(3, 3, 7, 'The themes of prejudice and justice are still relevant today.'),
(4, 4, 7, 'The simplicity of the prose is its strength.'),
(4, 4, 4, 'Scout''s innocence is heartwarming.'),
(4, 4, 6, 'I wish I could cast spells like Harry!'),
(4, 2, 8, 'The Jazz Age setting added depth to the story'),
(5, 3, 5, 'A classic that never gets old'),
(5, 4, 9, 'The magic of friendship shines through.'),
(5, 4, 3, 'The wisdom of the Alchemist stayed with me long after.'),
(5, 4, 10, 'A powerful portrayal of societal issues.'),
(6, 5, 6, 'I felt like I was on the journey with Santiago.'),
(6, 4, 1, 'The sense of wonder kept me turning pages.'),
(6, 5, 2, 'I was moved by Boo Radley''s story.'),
(6, 5, 4, 'The tragic love story touched my heart'),
(7, 3, 7, 'I dreamt of receiving my Hogwarts letter after reading this.'),
(7, 3, 8, 'I was enchanted by the parties and drama'),
(7, 3, 9, 'The courtroom scenes were gripping.'),
(7, 5, 10, 'The desert setting added to the mystical atmosphere.'),
(8, 5, 1, 'Gatsby''s obsession with Daisy is haunting'),
(8, 4, 8, 'Lee''s commentary on human nature is profound.'),
(8, 4, 7, 'The message about personal legend is profound.'),
(8, 3, 9, 'The adventures were thrilling from start to finish.'),
(9, 2, 9, 'Fitzgerald''s critique of the American Dream is powerful'),
(9, 3, 5, 'Dumbledore''s wisdom is timeless.'),
(9, 4, 6, 'Coelho''s philosophy on life is enlightening.'),
(9, 4, 4, 'This book made me question my own biases.'),
(10, 3, 10, 'The green light symbolizes so much more than just a beacon'),
(10, 1, 9, 'The sorting hat scene gave me chills.'),
(10, 5, 8, 'This book made me reflect on my own journey.'),
(10, 5, 7, 'Atticus Finch''s closing argument gave me chills.'),
(11, 5, 7, 'One of my favorite books so far, kept be hooked!'),
(11, 4, 3, 'Really enjoyed it, love thrillers'),
(11, 2, 6, 'Did not grip me, was bored half way through'),
(11, 4, 5, 'Such a classic!');

GO
