name: 'Flyway CI/CD Deployment'
on:
  push:
    branches:
      - main
env:
    DOCKER_IMAGE: redgate/flyway
    SCHEMAS: dbo
    MIGRATION_LOCATION: Flyway/migration
    FLYWAY_URL: ${{ secrets.FLYWAY_URL }}
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-20.04        
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - run: >-          
          docker run --rm
          --volume ${{ github.workspace }}/${{ env.MIGRATION_LOCATION }}:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.FLYWAY_URL }}"
          -user="${{ secrets.DB_USER }}"
          -password="${{ secrets.DB_PASSWORD }}"
          info -schemas="${{ env.SCHEMAS }}"
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/${{ env.MIGRATION_LOCATION }}:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.FLYWAY_URL }}"
          -user="${{ secrets.DB_USER }}"
          -password="${{ secrets.DB_PASSWORD }}"
          migrate -schemas="${{ env.SCHEMAS }}" -outOfOrder=true
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/${{ env.MIGRATION_LOCATION }}:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.FLYWAY_URL }}"
          -user="${{ secrets.DB_USER }}"
          -password="${{ secrets.DB_PASSWORD }}"
          info -schemas="${{ env.SCHEMAS }}"
